# The purpose of this .py is to check if the model created really learned the physics or just memorized it, by looking on the errors shown in the .csv file, generated by running this.
## Note: Before running this, you need to create some datas from the data_creation.py inorder to check the accuracy of the model.

import os
import torch
import numpy as np
import csv
from brain import Spectroscopic_Brain


def execute_arbitration(data_folder, model_weights_path, output_csv_name):
    print(f"Awakening the Neural Network from '{model_weights_path}'...")
    

    # 1. Hardware Targeting
    if torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
        

    # 2. Initiate and Load Memories
    brain = Spectroscopic_Brain().to(device)
    try:
        checkpoint = torch.load(model_weights_path, map_location=device)
        brain.load_state_dict(checkpoint["model_state_dict"])
    except FileNotFoundError:
        print(f"CRITICAL ERROR: Master weights '{model_weights_path}' not found.")
        return

    # Lock the brain. No training, only execution.
    brain.eval() 
    results_ledger = []

    print(f"\nIngesting physical matrices from: {data_folder}...")
    


    # 3. The Autonomous Loop
    for filename in sorted(os.listdir(data_folder)):
        if not filename.endswith(".npy"):
            continue
             
        # Parse the true physical answer strictly from your filename 
        # Example: "sample_000_fwhm_1.4523.npy" -> splits by "_" -> takes the last piece
        parts = filename.replace(".npy", "").split("_")
        true_fwhm = float(parts[-1])
        

        # Load the 245x245 raw photon matrix
        filepath = os.path.join(data_folder, filename)
        raw_matrix = np.load(filepath)
        

        # Convert to strict PyTorch 4D Tensor: [Batch=1, Channel=1, Height=245, Width=245]
        tensor_data = torch.tensor(raw_matrix, dtype=torch.float32).unsqueeze(0).unsqueeze(0).to(device)
        


        # 4. The Execution (Sever the calculus engine to save RAM)
        with torch.no_grad():
            prediction = brain(tensor_data)
            predicted_fwhm = prediction.item()
            
        # Calculate the absolute mathematical error
        absolute_error = abs(true_fwhm - predicted_fwhm)
        
        # Log the telemetry
        results_ledger.append([filename, true_fwhm, predicted_fwhm, absolute_error])
        print(f"Analyzed {filename} | True: {true_fwhm:.4f} | AI Guessed: {predicted_fwhm:.4f} | Error: {absolute_error:.4f}")




    # 5. The Excel Exporter / .csv Exported
    print(f"\nWriting telemetry directly to {output_csv_name}...")
    with open(output_csv_name, mode='w', newline='') as file:
        writer = csv.writer(file)
        # Write the headers for your Excel file
        writer.writerow(["Filename", "True_FWHM_Pixels", "AI_Predicted_FWHM", "Absolute_Error"])
        writer.writerows(results_ledger)
        
    print("SUCCESS: Arbitration complete. The data is ready for statistical graphing.")




if __name__ == "__main__":
    # Ensure these names match exactly what is saved on your hard drive
    
    execute_arbitration(
        data_folder="fabry_perot_data", 
        model_weights_path="spectroscopic_brain_undamaged.pth", 
        output_csv_name="pristine_results_pristine.csv"
    )